### ISSUE TITLE
How to generate a noise model ？

### ISSUE THREAD

**Issue by ze-n-g** [fengzhang427/LRD#1]
Thank you very much for open-sourcing your work. Will you consider open-sourcing the noise generation pre-training model and how to train the noise generation model in the code?

**Comment by fengzhang427** [comment]
Very grateful for following our work. Due to current company limitations, we are unable to further open source the noise generation model and training details. However, based on the details provided in the paper, our model is easy to reproduce. Please feel free to contact us at [fengzhangaia@hust.edu.cn](url) if you have any problems with the reproduction process.

**Comment by ze-n-g** [comment]
Thank you very much for your reply!
 When I read the paper, I did not find supplementary materials. If you can provide certain materials, I will be very grateful to you.
