### ISSUE TITLE
Details about the pre-trained denoise model

### ISSUE THREAD

**Issue by weiyi1991** [fengzhang427/LRD#3]
Hi, I am wondering how is the pre-trained denoise model trained. 
Is it first trained with the paired Noisy-GT images from dataset(SID or LRD), which refers to the score of "Paired data" in Table 1? During noise generator training, the denoise model is frozen. From my understanding, then the denoising model should be re-trained with generated noisy data pairs(only the generated pairs or the combination of generated pairs and original pairs), which refers to the score of "Ours" in Table 1.
Please correct me if I am wrong. Thanks.

**Comment by fengzhang427** [comment]
> Hi, I am wondering how is the pre-trained denoise model trained. Is it first trained with the paired Noisy-GT images from dataset(SID or LRD), which refers to the score of "Paired data" in Table 1? During noise generator training, the denoise model is frozen. From my understanding, then the denoising model should be re-trained with generated noisy data pairs(only the generated pairs or the combination of generated pairs and original pairs), which refers to the score of "Ours" in Table 1. Please correct me if I am wrong. Thanks.

Firstly, the Pre-trained Denoise-Net is trained using pairwise noisy-GT images from the dataset (SID or LRD) and frozen in the noise generator training.

Secondly, in the denoising training phase, we only utilize the generated noisy data pairs to train the denoising network from scratch, without using any real data.

Otherwise, our method improves the PSNR of the results by 1 dB and the SSIM by 0.02 when the real and generated data are mixed in a 1:1 ratio.

![image](https://github.com/fengzhang427/LRD/assets/67069761/ff1f886a-e6da-4520-a9b3-e549d65f68d8)
